### ISSUE TITLE
Facing issue with css link

### ISSUE THREAD

**Issue by Nikhil4752** [jamezmca/html-css-full-course#2]
Hi,

I have been following your videos and facing a small issue with the css link. As per the video your webpage was updated live but I require to save and reload again in order to get the changes. I did cross check the code, seems alright. Could you please advice if I am doing something wrong. Thanks in advance.

**Comment by jamezmca** [comment]
Hello! Let's see if we can fix that for you :P 

How far through the tutorial are you at current?

**Comment by Nikhil4752** [comment]
So I have only completed watching the initial bit describing the basics like tags.

**Comment by Nikhil4752** [comment]
Hi, 
I found the problem; I opened the index file straight from the folder instead of using the live server, my bad. Thanks for the prompt response and thanks for the great content!

**Comment by jamezmca** [comment]
My pleasure! Glad you got it all working :P
