### ISSUE TITLE
Automatic Tabbing

### ISSUE THREAD

**Issue by todonnell419** [jamezmca/html-css-full-course#3]
Hey team!

I'm sure anyone can help me with this, but I noticed a few times that when you were moving some of the div/section/html closing tags and it would automatically indent all of the lines that you have inside of it. How do you do that? I've never coded a day in my life and today's day one, so I'm sure this is easier than I think!

Example of when it happened: 30:10 when you first enter the first div tag

Thanks everyone!

**Comment by jamezmca** [comment]
Hello my friend! Welcome to programming :)

As for your question, it's very valid. What you are seeing is known as an auto-formatter and it's a part of the development experience in VSCode. Most programming languages can benefit from using an auto-formatter.

In VSCode, the command I use to get my code automatically formatted and indented is `option + shift + f` (on mac) and on windows it's probably `alt + shift + f`.

If you don't have an autoformatter installed, VSCode will prompt you to install one I believe! 

I hope that helps and let me know if you have any issues getting it working.

**Comment by todonnell419** [comment]
That's awesome and super easy, thank you!
